from __future__ import annotations

import streamlit as st

from model.run_model import ModelResult, run_model
from state.assumptions import Assumptions
from ui import outputs
from ui import inputs


def render(result: ModelResult, assumptions: Assumptions) -> Assumptions:
    st.markdown("# Financing & Debt")
    with st.expander("Key Assumptions", expanded=False):
        updated_assumptions = inputs.render_financing_key_assumptions(
            assumptions, "financing.assumptions"
        )
    output_container = st.container()
    updated_result = run_model(updated_assumptions)
    with output_container:
        outputs.render_financing_debt(updated_result, updated_assumptions)
        pension_obligation = updated_assumptions.balance_sheet.pension_obligations_eur
        info_rows = [
            (
                "Structural obligations not covered by CFADS: Pension liabilities",
                [outputs._format_money(pension_obligation)],
            )
        ]
        outputs._render_statement_table_html(
            info_rows,
            years=1,
            year_labels=["Value"],
        )
    with st.expander("Explain business & calculation logic", expanded=False):
        st.markdown(
            "**Business Purpose**\n"
            "This section assesses whether the operating cash profile is sufficient to service debt and where covenant headroom breaks under the plan.\n\n"
            "**Key Metrics & Definitions**\n"
            "CFADS (Cash Flow Available for Debt Service) represents cash generated by operations that is available to meet debt obligations.\n"
            "DSCR (Debt Service Coverage Ratio) measures coverage of total debt service by CFADS.\n\n"
            "**Calculation Logic**\n"
            "CFADS = EBITDA – Cash Taxes – Maintenance Capex ± Working Capital Change.\n"
            "Total Debt Service = Interest Expense + Scheduled Repayment.\n"
            "DSCR = CFADS / Total Debt Service.\n"
            "DSCR Headroom = DSCR – Minimum Required DSCR.\n"
            "A covenant breach is flagged when DSCR < Minimum Required DSCR for a given year.\n\n"
            "**Interpretation Guidelines**\n"
            "Minimum DSCR and years below covenant indicate how tight the debt structure is; persistent shortfalls imply refinancing or equity support is required.\n"
            "The transition year may appear weaker due to closing effects and initial debt drawdown timing.\n\n"
            "**Dependencies & Limitations**\n"
            "Results depend on the cashflow statement (EBITDA, taxes, capex, and working capital), the debt schedule (interest and repayment), and financing assumptions (interest rate and covenant threshold).\n"
            "This view does not model discretionary liquidity actions; it reflects the plan as built in the operating and financing assumptions."
        )
    return updated_assumptions
